name: BuildAndTest

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["2.0.2", "2.1.1", "stable"]

    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.version }}
      - run: "nimble build -y"
      - run: "nimble test -y"